/**
 * Writes SOURCES.md from src/data/sources.ts, listing which console profiles cite each source.
 * `node scripts/sources-md.ts --check` fails (for CI) when SOURCES.md is out of date.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { sources, type SourceId } from '../src/data/sources.ts'

const PROFILES = 'src/data/profiles'
const usedBy = new Map<SourceId, string[]>()

for (const entry of await readdir(PROFILES, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue
  const text = await readFile(`${PROFILES}/${entry.name}/profile.ts`, 'utf8')
  for (const id of Object.keys(sources) as SourceId[]) {
    if (text.includes(`'${id}'`)) usedBy.set(id, [...(usedBy.get(id) ?? []), entry.name])
  }
}

const rows = (Object.entries(sources) as [SourceId, (typeof sources)[SourceId]][]).map(
  ([id, s]) =>
    `| \`${id}\` | [${s.title}](${s.url}) | ${s.publisher} | ${s.accessed} | ${usedBy.get(id)?.join(', ') ?? '-'} |`,
)

const markdown = `# Sources

Every date, spec, price and sales figure on the site is backed by an entry below. Data in
\`src/data/profiles\` references these sources by id, and the source list is typed, so an unknown id
does not compile. A figure that cannot be verified, or where sources disagree, is flagged in the data
(\`uncertain: true\`) and shown with a visible "Disputed" label. It is never presented as settled fact.

Console pages number their sources in reading order and link each figure to its entry.

_This file is generated by \`node scripts/sources-md.ts\` from \`src/data/sources.ts\`. Do not edit it by hand._

| Id | Source | Publisher | Accessed | Cited by |
| -- | ------ | --------- | -------- | -------- |
${rows.join('\n')}

## Known disputes

- **NES US launch price.** Sources disagree, and prices varied by bundle. The site shows the Deluxe Set price reported by Wikipedia ($179.99) and flags it as disputed.
`

if (process.argv.includes('--check')) {
  const current = await readFile('SOURCES.md', 'utf8').catch(() => '')
  if (current !== markdown) {
    console.error('SOURCES.md is out of date. Run: node scripts/sources-md.ts')
    process.exit(1)
  }
} else {
  await writeFile('SOURCES.md', markdown)
}
